name:                lucid-view
version:             0.1.0.0
github:              "intolerable/lucid-view"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/intolerable/lucid-view#readme>

default-extensions:
  - BlockArguments
  - ExistentialQuantification
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - TypeFamilies

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - lucid2
  - mmorph
  - text
  - transformers

library:
  source-dirs: src

tests:
  lucid-view-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lucid-view
      - hspec
