resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/18.yaml

packages:
  - .

extra-deps:
  - git: https://github.com/intolerable/lucid.git
    commit: 3f1d5d1616f2798ddb16b3dc24dad625284d53e1
    subdirs:
      - lucid2

allow-newer: true
